// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scoreboard;

namespace Scoreboard.Migrations
{
    [DbContext(typeof(CandidateDbContext))]
    [Migration("20190527125336_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Scoreboard.CandidateInfo", b =>
                {
                    b.Property<string>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Score");

                    b.Property<string>("Score1");

                    b.Property<string>("Score2");

                    b.HasKey("Number");

                    b.ToTable("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
